### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by rwycuff** [emmetog/ansible-jenkins#17]
Why cant I deploy this and have security enabled.
even when I remove the auth strategy $Unsecure and Security realm from my config.xml
You role still leaves me wide open and adds the entries in the config.xml none the less.

**Comment by emmetog** [comment]
I'm not sure I understand your issue. Do you want to enable security in Jenkins when you deploy using this role? If so then I recommend that you deploy jenkins using this role, use the Jenkins web interface to set up the security as you want it, then copy Jenkins' xml files from the server and make this role provision them. Then whenever you deploy jenkins in the future the xml files will be set up exactly as you want them.

Is this what you're trying to do? If not please reopen and give more details of what you're trying to accomplish.

**Comment by rwycuff** [comment]
What I was trying to do is yes have security turned on.
But then add a security.groovy file with account setup in it.. 
This would be easy with the custom file option.
But your role only installs plugins and jobs via anonymous account or at least this is what I get every above configurations.
is there a way to tell curl what username and password to use in your role to lock this down?

**Comment by emmetog** [comment]
Sure, feel free to create a PR with your suggestions.

Another option that might interest you is to use a reverse proxy in front of jenkins which will be responsible for security and https. You should be able to do this with this role as is. If you're doing this you'll probably need to configure jenkins to listen on a port other than 80 and maybe firewall connections to this port from the outside.

**Comment by rwycuff** [comment]
So you are saying leave it open as you have it and use ngnix or something of that sort to secure it with proxy?

**Comment by emmetog** [comment]
Yes, it's an option.
