### ISSUE TITLE
url openerror during plugin installation

### ISSUE THREAD

**Issue by sarathcakurathi** [emmetog/ansible-jenkins#26]
## Expected Behavior
Jenkins-crumb received and proceed with plugin installation

## Actual Behavior
fatal: [localhost]: FAILED! => {"changed": false, "content": "", "msg": "Status code was not [200, 404]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"}

I am getting crumb with curl command, with ansible it is failing with above error - 
curl "http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"
Jenkins-Crumb:cd50b99693fa890d69f70cd7ead94ca3

Could you please check this error

**Comment by darenjacobs** [comment]
I'm getting the same thing.  Is there a resolution for this?

**Comment by tjoen** [comment]
Found the blocking line.
Edit "wait-for-start.yml"
Comment out (or remove):  
delegate_to: localhost

After the edit the role should work perfectly.

**Comment by emmetog** [comment]
Could you check if it's resolved now? It should be fixed in https://github.com/emmetog/ansible-jenkins/commit/40259002ccc1c4a7e5da6db4be97841d77e634cb

**Comment by tjoen** [comment]
Yup, that works for me.... 

Thanks emmetog!

**Comment by emmetog** [comment]
Great, thanks @tjoen
